highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


url: http://msdeep14.github.io/
baseurl: http://msdeep14.github.io/
title: Mandeep Singh
author: Mandeep Singh
description: Homepage of Mandeep Singh.
avatar: profile.jpg
email: mandeepsingh_14070@aitpune.edu.in
github: msdeep14 # username
twitter: msdeep14
linkedin: mandeep-singh-2476b6a5

# needed for travis-ci build
exclude: [vendor]
