highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


url: https://msdeep14.github.io/
baseurl: https://msdeep14.github.io/
title: Mandeep Singh
author: Mandeep Singh
description: Homepage of Mandeep Singh.
avatar: profile.jpg
email: mandeepsingh_14070@aitpune.edu.in
github: msdeep14 # username
twitter: msdeep14
linkedin: msdeep14

# needed for travis-ci build
exclude: [vendor]
